apiVersion: v1
kind: Service
metadata:
  name: auth-switch-service
spec:
  selector:
    app: auth-switch-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
