server:
  port: 8080
  
  
spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/register/**, /oauth/token/**

        - id: auth-switch-service
          uri: http://auth-switch-service:8082
          predicates:
            - Path=/authorize, /secure/**,  /api/v1/transaction/**

      default-filters:
        - AddResponseHeader=X-Gateway-Filter, applied

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

# Optional CORS config
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO

